on:
  push:
    paths-ignore:
      - 'readme.md'
      - '.gitignore'
    branches:
      - main
  
jobs:
  build:
  
   runs-on: ubuntu-latest
  
   steps:
    - uses: actions/checkout@v1
    - name: Install Prerequisites
      run: Install-Module -Name PSScriptAnalyzer, MiniGraph, MarkdownPrince -Force
      shell: pwsh
    - name: Validate
      run: Invoke-ScriptAnalyzer -Path . -Recurse -Fix -EnableExit -Severity Error,ParseError,Warning
      shell: pwsh
    - name: Build
      run: Publish-Script -Path ./Export-OneNote.ps1 -NuGetApiKey $env:APIKEY -Repo PSGallery
      shell: pwsh
      env:
        APIKEY: ${{ secrets.ApiKey }}